version: '3'
#networks:
#  open5gsnetwork:
#    ipam:
#      config:
#        - subnet: 192.168.0.0/24
services:
  gnb1:
    image: ping2balaji/ueransim_docker:v1
    container_name: gnb1
    network_mode: "host"
    command: 
      - gnb
    environment:
      AMF_HOSTNAME: amf
      GNB_HOSTNAME: gnb1
      MCC: '315'
      MNC: '010'
      NCI: '0x000000010'
      TAC: 12345
      GNB_ADDR: 10.0.4.225
      AMF_ADDR: 10.0.4.202
      SST: 0x01
      SD: 0x19CDE1
#    networks:
#      open5gsnetwork:
#        ipv4_address: 192.168.0.161
